services:
  postgres:
    image: postgres:15
    container_name: aton-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aton
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aton"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: aton-postgres-data
